name: Continuous Integration

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Installing project dependencies
        run: |
          npm ci
      - name: Lint
        run: |
          npm run lint
      - name: Format Check
        run: |
          npm run format:check
      # TODO: add typechecking
      # TODO: restore testing
      # - name: Test
      #   run: |
      #     npm run test
      - name: Build
        run: |
          npm run build
      # TODO: restore storybook
      # - name: Storybook
      #   run: |
      #     npm run storybook:build
