name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "production"
    permissions:
      id-token: write

    steps:
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Installing project dependencies
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Deploy to Production Environment
        env:
          API_BACKEND_HOSTNAME: ${{ secrets.API_BACKEND_HOSTNAME }}
        run: |
          npm run deploy:prod
